Add logging and update fuel-bootstrap-image-builder
Change-Id: I397710246569d268da0d813c37a97823e084f7ff

diff --git a/deployment_scripts/fuel-bootstrap-image-builder/bin/fuel-bootstrap-image b/deployment_scripts/fuel-bootstrap-image-builder/bin/fuel-bootstrap-image
--- a/deployment_scripts/fuel-bootstrap-image-builder/bin/fuel-bootstrap-image
+++ b/deployment_scripts/fuel-bootstrap-image-builder/bin/fuel-bootstrap-image
@@ -8,7 +8,7 @@ datadir="${bindir%/*}/share/fuel-bootstrap-image"
 global_conf="/etc/fuel-bootstrap-image.conf"
 [ -r "$global_conf" ] && . "$global_conf"
 
-[ -z "$MOS_VERSION" ] && MOS_VERSION="7.0"
+[ -z "$MOS_VERSION" ] && MOS_VERSION="8.0"
 [ -z "$DISTRO_RELEASE" ] && DISTRO_RELEASE="trusty"
 [ -z "$MIRROR_DISTRO" ] && MIRROR_DISTRO="http://archive.ubuntu.com/ubuntu"
 [ -z "$MIRROR_MOS" ] && MIRROR_MOS="http://mirror.fuel-infra.org/mos-repos/ubuntu/$MOS_VERSION"
@@ -16,17 +16,15 @@ global_conf="/etc/fuel-bootstrap-image.conf"
 [ -z "$ARCH" ] && ARCH="amd64"
 [ -z "$DESTDIR" ] && DESTDIR="/var/www/nailgun/bootstrap/ubuntu"
 
-BOOTSTRAP_FUEL_PKGS_DFLT="openssh-server ntp"
-
 # Packages required for the master node to discover a bootstrap node
+BOOTSTRAP_FUEL_PKGS_DFLT="openssh-client openssh-server ntp mcollective nailgun-agent nailgun-mcagents nailgun-net-check fuel-agent"
+[ -z "$BOOTSTRAP_FUEL_PKGS" ] && BOOTSTRAP_FUEL_PKGS="$BOOTSTRAP_FUEL_PKGS_DFLT"
+
 if [ -z "$BOOTSTRAP_IRONIC" ]; then
-	BOOTSTRAP_FUEL_PKGS_DFLT="$BOOTSTRAP_FUEL_PKGS_DFLT openssh-client mcollective nailgun-agent nailgun-mcagents nailgun-net-check"
 	GONFIG_SOURCE="$datadir/ubuntu/files/"
 else
 	GONFIG_SOURCE="$datadir/ubuntu/files.ironic/"
 fi
-
-[ -z "$BOOTSTRAP_FUEL_PKGS" ] && BOOTSTRAP_FUEL_PKGS="$BOOTSTRAP_FUEL_PKGS_DFLT"
 
 if [ -n "$http_proxy" ]; then
 	export HTTP_PROXY="$http_proxy"
@@ -256,12 +254,33 @@ make_utf8_locale ()
 	chroot "$root" /bin/sh -c "locale-gen en_US.UTF-8 && dpkg-reconfigure locales"
 }
 
+# XXX: CentOS version of debootstrap produces a broken /dev:
+# /dev/fd is a directory instead of a symlink to /proc/self/fd
+dev_fixup ()
+{
+	local root="$1"
+	if [ -z "$root" ]; then
+		echo "*** Error: $MYSELF: dev_fixup: \$root is not specified" >&2
+		exit 1
+	fi
+	mkdir -p -m755 "$root/dev"
+	if [ ! -L "$root/dev/fd" ]; then
+		rm -rf "$root/dev/fd"
+		# Ask MAKEDEV to re-create /dev/fd, /dev/stdin, etc
+		chroot "$root" /bin/sh -c "cd /dev && MAKEDEV fd"
+	fi
+	if [ ! -c "$root/dev/null" ]; then
+		# basic device nodes are missing => create them
+		chroot "$root" /bin/sh -c "cd /dev && MAKEDEV std"
+	fi
+}
+
 copy_conf_files ()
 {
 	local root="$1"
 	local sdir="$2"
 	rsync -rlptDK "${sdir}" "${root%/}"
-	sed -i $root/etc/shadow -e '/^root/c\root:$$6$$oC7haQNQ$$LtVf6AI.QKn9Jb89r83PtQN9fBqpHT9bAFLzy.YVxTLiFgsoqlPY3awKvbuSgtxYHx4RUcpUqMotp.WZ0Hwoj.:15441:0:99999:7:::'
+	sed -i $root/etc/shadow -e '/^root/c\root:$6$oC7haQNQ$LtVf6AI.QKn9Jb89r83PtQN9fBqpHT9bAFLzy.YVxTLiFgsoqlPY3awKvbuSgtxYHx4RUcpUqMotp.WZ0Hwoj.:15441:0:99999:7:::'
 }
 
 install_ssh_keys ()
@@ -373,6 +392,7 @@ build_image ()
 	chmod 755 "$root"
 	suppress_services_start "$root"
 	run_debootstrap "$root"
+	dev_fixup "$root"
 	suppress_services_start "$root"
 	propagate_host_resolv_conf "$root"
 	make_utf8_locale "$root"
